model:
  contrastive:
    attn_feature_dim: 128
    temperature: 0.7

  image:
    model_name: 'resnet50'
    pretrained: true
    embed_dim: 512
  
  context:
    tokenizer: 'roberta_tokenizer'
    encoder: 'roberta'
    fine_tune: true
    embed_dim: 256


  caption:
    tokenizer: 'roberta_tokenizer'
    encoder: 'roberta'
    fine_tune: true
    embed_dim: 256

data:
  dataset_name: 'augmented_context'
  json_file: 'train_first_40k.json'
  num_debug_samples: 10000
  train_split: 0.8
  val_split: 0.2

train:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  num_workers: 4
  prefetch_factor: 2

debug: true